### PR TITLE
Update README.md with deployment options

### PR DESCRIPTION
**Pull request by kingzbauer**

### CODE REVIEW

**Review by NajeebTyson — APPROVED** [review]
LGTM!

**Review by zubair-nabi — COMMENTED** [review]
Isn't this README out of sync now? https://github.com/Kaleidoscope-Inc/blueprint-configurator/blob/main/aws/README.md

Should we move the AWS specific steps from the outer README into the inner AWS one? That way things can be consistent?

**Comment by zubair-nabi** [comment]
> Isn't this README out of sync now? https://github.com/Kaleidoscope-Inc/blueprint-configurator/blob/main/aws/README.md
> 
> Should we move the AWS specific steps from the outer README into the inner AWS one? That way things can be consistent?

Also, in that README should we provide a table with all the vars and their description? Because right now as a consumer, I have to go through the Terraform itself to figure this out.

**Comment by kingzbauer** [comment]
@zubair-nabi  updated!

**Review by zubair-nabi — APPROVED** [review]
LGTM!

**Pull request merged**
